source('lib/code.R')
source('lib/rnd-beta.R')
library(parallel)
library(doParallel)

args <- commandArgs(trailingOnly=TRUE)

N <- 1E4
n <- as.integer(args[2])
m <- 8
inst <- as.integer(args[3])

message("n ", n)
message("inst ", inst)

set.seed(1911)

# 8*15 matrix (alternative*criterion) of measurement distribution choices
# Generated by: dput(sapply(1:15, function(i) { sample(9, 8) }))
meas.choice <- 
structure(c(7L, 2L, 5L, 8L, 6L, 3L, 9L, 1L, 4L, 7L, 5L, 6L, 1L, 
            2L, 3L, 8L, 7L, 6L, 5L, 1L, 4L, 9L, 8L, 3L, 5L, 1L, 3L, 4L, 7L, 
            8L, 6L, 9L, 6L, 2L, 5L, 1L, 7L, 8L, 4L, 9L, 7L, 1L, 3L, 5L, 2L, 
            4L, 8L, 6L, 5L, 6L, 3L, 4L, 1L, 9L, 7L, 2L, 5L, 2L, 8L, 9L, 4L, 
            1L, 7L, 6L, 7L, 4L, 6L, 9L, 2L, 8L, 1L, 3L, 5L, 8L, 2L, 4L, 7L, 
            9L, 6L, 3L, 7L, 4L, 2L, 9L, 1L, 6L, 5L, 8L, 3L, 6L, 8L, 9L, 1L, 
            5L, 7L, 4L, 9L, 1L, 2L, 7L, 5L, 4L, 6L, 3L, 7L, 8L, 6L, 4L, 5L, 
            3L, 1L, 2L, 2L, 9L, 8L, 4L, 7L, 6L, 5L, 1L),
          .Dim = c(8L, 15L))


meas <- array(NA, dim=c(N, m, n))
for (j in 1:n) {
  for (i in 1:m) {
    d <- meas.choice[i, j]
    meas[ , i, j] <- rbeta(N, a[d], b[d])
  }
}

## Each node does 10k
## so total 100 instances per n
N.all <- 1E6

my.range.start <- function(index) {
  1 + ((index-1) * 10000)
}

constr <- list(constr=matrix(NA, nrow=0, ncol=n), dir=rep("<=", 0), rhs=rep(0, 0))

all.planes <- readRDS(paste0('data/convergence-planes.n', n, '.rds'))
my.planes <- all.planes[my.range.start(inst):(my.range.start(inst+1)-1)]

cl <- makeCluster(detectCores())
registerDoParallel(cl)

error.func <- error.func.entropy(equal.w.prob=FALSE, entropy=smaa.entropy.choice)

print(system.time(
                  best <- best.cutting.plane(constr, meas, my.planes, error.func=error.func)
                  ))
print("Entropies estimated")

stopCluster(cl)

saveRDS(best$entropies, paste0('data/convergence-entropies.n', n, '.', inst, '.rds'))
